import json
import math
import os
from typing import Dict, List, Tuple, Optional
import numpy as np
from planner.planner import FlowAwarePlanner, CustomerState

"""
XGB policy-backed planner.

- Loads artifacts generated by train_xgb_policy.py
- Subclasses FlowAwarePlanner and consults the policy to choose:
    * charge-now vs skip
    * target charge_to (short vs slightly longer top-ups on GREEN STATIONS)
- Falls back to vanilla FlowAwarePlanner behavior if model missing.

Env:
  POLICY_DIR          path with policy_xgb.json + policy_features.json (default ./model_artifacts)
  POLICY_CHARGE_BIAS  float, add to predicted reward when choosing 'charge' (default 0.0)
"""

try:
    import xgboost as xgb
except Exception:
    xgb = None  # fallback if missing


class _XGBPolicy:
    def __init__(self, policy_dir: str):
        self.model = None
        self.cols: List[str] = []
        self.charge_bias = float(os.environ.get("POLICY_CHARGE_BIAS", "0.0"))
        if xgb is None:
            return
        mpath = os.path.join(policy_dir, "policy_xgb.json")
        fpath = os.path.join(policy_dir, "policy_features.json")
        if os.path.exists(mpath) and os.path.exists(fpath):
            try:
                self.model = xgb.XGBRegressor()
                self.model.load_model(mpath)
                with open(fpath, "r") as f:
                    self.cols = json.load(f)
            except Exception:
                self.model = None
                self.cols = []

    def ready(self) -> bool:
        return self.model is not None and len(self.cols) > 0

    def _vectorize(self, feats: Dict) -> np.ndarray:
        x = np.zeros((1, len(self.cols)), dtype=float)
        for i, c in enumerate(self.cols):
            x[0, i] = float(feats.get(c, 0.0))
        return x

    def predict_reward(self, feats: Dict, action: str) -> float:
        """
        Approximate Q(state, action) with a single regressor by
        encoding the action as a binary feature:

          action_is_charge = 1 for "charge"
                           = 0 for "skip"

        Action in {"charge","skip"}.
        """
        if not self.ready():
            return 0.0

        # Copy so we don't mutate caller's dict
        feats_local = dict(feats)

        # Inject action flag expected by the trained model
        if action == "charge":
            feats_local["action_is_charge"] = 1.0
        else:
            feats_local["action_is_charge"] = 0.0

        x = self._vectorize(feats_local)
        y = float(self.model.predict(x)[0])

        # Optional bias: small extra incentive to charge
        if action == "charge":
            y += self.charge_bias

        return y


class FlowAwarePlannerXGB(FlowAwarePlanner):
    def __init__(self, map_obj: dict):
        super().__init__(map_obj)
        policy_dir = os.environ.get("POLICY_DIR", "./model_artifacts")
        self._policy = _XGBPolicy(policy_dir)

        # ML will steer the pattern
        self.MIN_SOC = max(0.18, self.MIN_SOC)
        self.MAX_SOC = max(0.80, self.MAX_SOC)

    def _policy_features(
            self,
            persona: str,
            is_green: int,
            station_speed_kw: float,
            queue_len: float,
            soc: float,
            dist_to_goal_km: float,
    ) -> Dict:
        """
        Build feature dict aligned with policy_trainer:
          - is_green, station_speed_kw, queue_len, soc, dist_to_goal_km
          - persona_* one-hot
        (action_is_charge will be injected at predict time)
        """
        p = (persona or "neutral").lower()
        feats = {
            "is_green": float(is_green),
            "station_speed_kw": float(station_speed_kw),
            "queue_len": float(queue_len),
            "soc": float(soc),
            "dist_to_goal_km": float(dist_to_goal_km),
        }
        feats[f"persona_{p}"] = 1.0
        return feats

    # Policy/Heuristic choosers (node-based GREEN)
    def _choose_station_with_policy(
            self,
            node_tick_path,
            nodes_seq,
            cum_d,
            kwh_left: float,
            cons: float,
            dist_cost: float,
            tick: int,
            cap: float,
            persona: str,
    ):
        """
        Learned policy pick station and action.
        Returns (nid, t_arrive, action_id, need_kwh) or None.

        persona: string like "CostSensitive", "EcoConscious", etc.,
                 used to build persona_* one-hot features.
        """
        if not (hasattr(self, "_policy") and self._policy and self._policy.ready()):
            return None

        meta = []  # (nid, t_arrive, km_to_station, soc_at_station, green, station_speed_kw, queue_pressure, km_after, free)
        EPS = 1e-9

        for nid in nodes_seq:
            st = self.station_by_node.get(nid)
            if not st:
                continue
            t_arrive = next((t_ for n_, t_ in node_tick_path if n_ == nid), None)
            if t_arrive is None:
                continue

            km_to_station = cum_d.get(nid, 0.0)
            kwh_to_station = km_to_station * cons
            if kwh_left < kwh_to_station * 1.05:
                continue  # not reachable

            # NODE-BASED green
            green = 1.0 if getattr(st, "is_green", False) else 0.0

            queue_pressure = 0.0
            if st.total > 0:
                queue_pressure = max(0, st.total - st.free) / float(st.total)

            soc_at_station = max(0.0, (kwh_left - kwh_to_station) / max(EPS, cap))
            km_after = max(0.0, dist_cost - km_to_station)

            meta.append(
                (
                    nid,
                    t_arrive,
                    km_to_station,
                    soc_at_station,
                    green,
                    float(st.speed_kw),
                    queue_pressure,
                    km_after,
                    float(st.free),
                )
            )

        if not meta:
            return None

        # Compare "charge" vs "skip" for each candidate using the policy.
        action_ids = []
        try:
            for (
                    nid,
                    t_arrive,
                    km_to_station,
                    soc_at_station,
                    green,
                    station_speed_kw,
                    queue_pressure,
                    km_after,
                    free_slots,
            ) in meta:
                feats = self._policy_features(
                    persona=persona,
                    is_green=green,
                    station_speed_kw=station_speed_kw,
                    queue_len=queue_pressure,
                    soc=soc_at_station,
                    dist_to_goal_km=km_after,
                )
                # "free" isn't used by the model but harmless to include
                feats["free"] = free_slots

                r_charge = self._policy.predict_reward(feats, "charge")
                r_skip = self._policy.predict_reward(feats, "skip")
                action_ids.append(1 if r_charge >= r_skip else 0)  # 1=charge, 0=skip
        except Exception:
            return None

        # Translate action to kWh for the first station where policy says "charge"
        for idx, action_id in enumerate(action_ids):
            if action_id == 0:
                # skip -> let heuristic layer decide later
                continue

            (
                nid,
                t_arrive,
                km_to_station,
                soc_at_station,
                green,
                station_speed_kw,
                queue_pressure,
                km_after,
                free_slots,
            ) = meta[idx]

            st = self.station_by_node[nid]
            kwh_to_station = km_to_station * cons
            kwh_rem_after_station = max(0.0, kwh_left - kwh_to_station)

            kwh_after = km_after * cons

            buffer = 0.12
            target_after = kwh_after * (1.0 + buffer)
            min_required = max(0.0, target_after - kwh_rem_after_station)

            # Try to reach ~0.70 SOC when green, else ~0.62
            base_target_soc = 0.70 if getattr(st, "is_green", False) else 0.62
            target_kwh = max(0.0, base_target_soc * cap - kwh_rem_after_station)

            need_kwh = max(min_required, target_kwh, 0.05 * cap)
            return (nid, t_arrive, int(action_id), float(need_kwh))

        return None

    def _choose_station_heuristic(
            self,
            node_tick_path,
            nodes_seq,
            cum_d,
            kwh_left: float,
            cons: float,
            dist_cost: float,
            tick: int,
            cap: float,
    ):
        """
        Baseline heuristic station picker, returns (nid, t_arrive, need_kwh) or None.
        Prefers GREEN STATIONS (node flag), low queue, reachable-on-path; sizes charge to finish leg + buffer.
        """
        best = None  # (score, (nid, t_arrive, need_kwh))
        for nid in nodes_seq:
            st = self.station_by_node.get(nid)
            if not st:
                continue

            t_arrive = next((t_ for n_, t_ in node_tick_path if n_ == nid), None)
            if t_arrive is None:
                continue

            km_to_station = cum_d.get(nid, 0.0)
            kwh_to_station = km_to_station * cons
            if kwh_left < kwh_to_station * 1.05:
                continue  # not reachable

            km_after = max(0.0, dist_cost - km_to_station)
            kwh_after = km_after * cons
            kwh_rem_after_station = max(0.0, kwh_left - kwh_to_station)

            BUFFER_FINISH = 0.12
            target_after = kwh_after * (1.0 + BUFFER_FINISH)
            need_kwh = max(0.0, target_after - kwh_rem_after_station)

            # NODE-BASED green score
            green = 1.0 if getattr(st, "is_green", False) else 0.0
            queue_pressure = 0.0
            if st.total > 0:
                queue_pressure = max(0, st.total - st.free) / float(st.total)
            speed_benefit = math.log1p(max(st.speed_kw, 0.0))

            score = (1.0 * green) + (0.5 * speed_benefit) - (0.7 * queue_pressure)
            cand = (score, (nid, t_arrive, max(need_kwh, 0.05 * cap)))
            if (best is None) or (score > best[0]):
                best = cand

        return None if best is None else best[1]

    # Planning step
    def _plan_single(self, cust, tick: int):
        """
        Patched planning step that safely falls back when policy returns None.
        """
        soc = max(0.0, float(cust.charge_remaining))
        cap = float(cust.max_charge)
        cons = max(1e-6, float(cust.consumption_per_km))

        # CA* main corridor
        node_tick_path = self._ca_star(cust.from_node, cust.to_node, tick)
        nodes_seq = [n for (n, _t) in node_tick_path]
        if len(nodes_seq) == 1 and nodes_seq[0] == cust.from_node:
            return None

        # path length
        dist_cost = 0.0
        for i in range(len(nodes_seq) - 1):
            u, v = nodes_seq[i], nodes_seq[i + 1]
            L = next((L for w, L, _ in self.adj.get(u, []) if w == v), 0.0)
            dist_cost += L

        # cumulative distances
        cum_d = {nodes_seq[0]: 0.0}
        for i in range(1, len(nodes_seq)):
            u, v = nodes_seq[i - 1], nodes_seq[i]
            L = next((L for w, L, _ in self.adj.get(u, []) if w == v), 0.0)
            cum_d[v] = cum_d[u] + L

        # Policy choice (node-based green, persona-aware)
        picked = self._choose_station_with_policy(
            node_tick_path=node_tick_path,
            nodes_seq=nodes_seq,
            cum_d=cum_d,
            kwh_left=soc * cap,
            cons=cons,
            dist_cost=dist_cost,
            tick=tick,
            cap=cap,
            persona=cust.persona,
        )

        if picked is None:
            heur = self._choose_station_heuristic(
                node_tick_path=node_tick_path,
                nodes_seq=nodes_seq,
                cum_d=cum_d,
                kwh_left=soc * cap,
                cons=cons,
                dist_cost=dist_cost,
                tick=tick,
                cap=cap,
            )
            if heur is None:
                return None
            nid, t_arrive, need_kwh = heur
            action = -1  # heuristic marker
        else:
            nid, t_arrive, action, need_kwh = picked

        st = self.station_by_node.get(nid)
        if st is None:
            return None

        # Reserve edge-time + charger
        self._reserve_edge_sequence(node_tick_path, nid)
        charge_ticks = self._charge_duration_ticks(need_kwh, st.speed_kw)
        _ = self._reserve_charger(nid, t_arrive, charge_ticks, st.free)

        # Final SoC
        km_to_station = cum_d.get(nid, 0.0)
        kwh_to_station = km_to_station * cons
        kwh_rem_after_station = max(0.0, soc * cap - kwh_to_station)
        charge_to = (kwh_rem_after_station + need_kwh) / max(cap, 1e-9)

        # Clamp to planner bounds
        charge_to = max(self.MIN_SOC, min(self.MAX_SOC, charge_to))

        return {
            "customerId": cust.id,
            "chargingRecommendations": [{"nodeId": nid, "chargeTo": round(float(charge_to), 3)}],
        }
